language: csharp
solution: Regulus.sln

install:  
   # -sudo apt-get install mono-devel mono-gmcs nunit-console

  - nuget restore Regulus.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Regulus.sln  
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Test/GhostProviderGeneratorTests/bin/Release/GhostProviderGeneratorTests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Test/PureLibTest/bin/Release/RegulusLibraryTest.dll

