language: csharp

solution: ./Regulus.sln

notifications:      
    email: false
    
install:  
  - nuget restore Regulus.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Regulus.sln  
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Test/RegulusBehaviourTree.Tests/bin/Release/RegulusBehaviourTree.Tests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Test/PureLibTest/bin/Release/RegulusLibraryTest.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Test/Regulus.SerializationTests/bin/Release/Regulus.SerializationTests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Test/RegulusProtocolTests/bin/Release/RegulusProtocolTests.dll
  

before_deploy:
    - mkdir "./RegulusPack"
    
    - mkdir "./RegulusPack/Library"
    - mkdir "./RegulusPack/Library/BehaviourTree"
    - mkdir "./RegulusPack/Library/Server"
    - mkdir "./RegulusPack/Library/Client"

    - mkdir "./RegulusPack/Tool"
    - mkdir "./RegulusPack/Tool/Server"
    - mkdir "./RegulusPack/Tool/ProtocolBuilder"


    - cp "./Library/RegulusBehaviourTree/bin/Release/*.*" "./RegulusPack/Library/BehaviourTree" 

    - cp "./Library/RemotingNativeGhost/bin/Release/*.*" "./RegulusPack/Library/Client" 

    - cp "./Library/RemotingNativeSoul/bin/Release/*.*" "./RegulusPack/Library/Server" 

    - cp "./Tool/Server/bin/Release/*.*" "./RegulusPack/Tool/Server" 
    - cp "./Tool/Regulus.Remoting.Unity.ProtocolBuilder/bin/Release/*.*" "./RegulusPack/Tool/ProtocolBuilder" 


  
deploy:              
  
    provider: releases 
    api_key:  "82a333e58c30c0a8de3724661f090196e5f01bc3"           
    
    file: RegulusPack/*.*
    file_glob: true
    skip_cleanup: true     
    on:     
        tags: true       
    
    
    
