language: csharp
solution: Regulus.sln

install:  
   # -sudo apt-get install mono-devel mono-gmcs nunit-console

  - nuget restore Regulus.sln
  

script:
  - xbuild /p:Configuration=Release Regulus.sln  

