AppVeyor
PROJECTS
ENVIRONMENTS
DOCS
SUPPORT
 JC
Regulus

LATEST BUILD HISTORY DEPLOYMENTS SETTINGS
General
Environment
Build
Tests
Artifacts
Deployment
NuGet
Notifications
Permissions
Badges
Export YAML
Delete project
Export project configuration to YAML

Below is appveyor.yml for your current project configuration. To store versioned project configuration along with your sources download appveyor.yml and commit it to the root of your code repository.

Download appveyor.yml
version: 0.3.{build}
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_test:
- cmd: build_package.cmd
artifacts:
- path: artifact\Library\Server
  name: Server
  type: WebDeployPackage
- path: artifact\Library\Client
  name: Client
  type: WebDeployPackage
- path: artifact\Library\BehaviourTree
  name: BehaviourTree
  type: WebDeployPackage
- path: artifact\Tool
  name: Tool
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: /AfJAx3kxJ0kcGiZVCl5U7v3f9Z0qIDDN5L+ckDjxzkULqDK0fhwWVgcqRNukVln
  artifact: '**\*.zip'
  draft: true
after_deploy:
- ps: >-
    Get-ChildItem BehaviourTree.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }



    Get-ChildItem Client.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }



    Get-ChildItem Server.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }



    Get-ChildItem Tool.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
 