version: 0.3.{build}
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_test:
- cmd: build_package.cmd
artifacts:
- path: artifact\Library\Server
  name: Server
- path: artifact\Library\Client
  name: Client
- path: artifact\Library\BehaviourTree
  name: BehaviourTree
- path: artifact\Tool
  name: Tool
deploy:
- provider: GitHub
  auth_token:
    secure: /AfJAx3kxJ0kcGiZVCl5U7v3f9Z0qIDDN5L+ckDjxzkULqDK0fhwWVgcqRNukVln
  artifact: RegulusArtfact
  draft: true