version: 0.3.{build}
configuration: Release
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- ps: >-
    Get-ChildItem **\BehaviourTree.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }



    Get-ChildItem **\Client.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }



    Get-ChildItem **\Server.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }



    Get-ChildItem **\Tool.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
after_test:
- cmd: build_package.cmd
artifacts:
- path: artifact\Library\Server
  name: Server
- path: artifact\Library\Client
  name: Client
- path: artifact\Library\BehaviourTree
  name: BehaviourTree
- path: artifact\Tool
  name: Tool
- path: '**\RegulusLibrary.nupkg'
  name: NupkgRegulusLibrary
- path: '**\RegulusRemoting.nupkg'
  name: NupkgRegulusRemoting
- path: '**\RegulusRemotingServer.nupkg'
  name: NupkgRegulusRemotingServer
deploy:
- provider: GitHub
  auth_token:
    secure: /AfJAx3kxJ0kcGiZVCl5U7v3f9Z0qIDDN5L+ckDjxzkULqDK0fhwWVgcqRNukVln
  draft: true
- provider: NuGet
  server: http://www.nuget.org/api/v2/
  api_key:
    secure: MpSZN9rbs/UO67xFMkdfsETL16yG2KY0h3S53s13iG8WOFPamFIXg44GpbM4T7qX