version: 0.3.{build}
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_test:
- cmd: build_package.cmd
artifacts:
- path: artifact\Library\Server
  name: Server
  type: WebDeployPackage
- path: artifact\Library\Client
  name: Client
  type: WebDeployPackage
- path: artifact\Library\BehaviourTree
  name: BehaviourTree
  type: WebDeployPackage
- path: artifact\Tool
  name: Tool
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: /AfJAx3kxJ0kcGiZVCl5U7v3f9Z0qIDDN5L+ckDjxzkULqDK0fhwWVgcqRNukVln
  artifact: '**\*.zip'
  draft: true
after_deploy:
- ps: >-
    Push-AppveyorArtifact artifact\Library\BehaviourTree.zip

    Push-AppveyorArtifact artifact\Library\Client.zip

    Push-AppveyorArtifact artifact\Library\Server.zip

    Push-AppveyorArtifact artifact\Tool.zip